parameters:
#    babaganoush_datatables.example.class: Babaganoush\DataTablesBundle\Example

services:
#    Babaganoush_datatables.example:
#        class: %2levelsabove_flotr2.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
